[Settings]
# Replace these with your actual directory paths
source_dir = /mnt/NAS/cleanmusic/music2/music/Earth Wind  Fire/Earth Wind & Fire/Greatest Hits/
target_dir = /mnt/NAS/cleanmusic/music2/music/Earth Wind  Fire/Earth Wind & Fire/Greatest Hits/new/