[Settings]
# Replace these with your actual directory paths
source_dir = /mnt/NAS/cleanmusic/music2/R-Music/AudioRanger Music/Duplicates/Compilations/Brazilian Groove/
target_dir = /mnt/NAS/cleanmusic/NewMaster/Various Artists/Putumayo Presents Brazilian Groove/